version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    container_name: backend-container
    networks:
      - mern-stack-network
    volumes:
      - ./backend:/app/frontend
    depends_on:
      - db
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: frontend-container
    networks:
      - mern-stack-network
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  db:
    image: mongo:latest
    
    ports:
      - 27017:27017
    
    container_name: mongo-container

    networks:
      - mern-stack-network

    volumes:
      - mongoData:/data/db

networks:
  mern-stack-network:

volumes:
  mongoData:

